Also check for jq.

diff --git a/terraform-credentials-op b/terraform-credentials-op
--- a/terraform-credentials-op
+++ b/terraform-credentials-op
@@ -2,7 +2,6 @@
 # Install 1Password CLI and jq.
 #
 # https://www.terraform.io/docs/internals/credentials-helpers.html
-#set -euo pipefail
 set -uo pipefail
 RETVAL=-1
 
@@ -24,6 +23,12 @@ if ! command -v op &>/dev/null
 then
   echo "ERROR: op could not be found. Please install 1Password CLI and add to the PATH." 1>&2
   exit 11
+fi
+
+if ! command -v jq &>/dev/null
+then
+  echo "ERROR: jq could not be found. Please install jq and add to the PATH." 1>&2
+  exit 12
 fi
 
 op whoami &>/dev/null
