Add checks for op binary and op signin.

diff --git a/terraform-credentials-op b/terraform-credentials-op
--- a/terraform-credentials-op
+++ b/terraform-credentials-op
@@ -14,11 +14,24 @@ print_help() {
 
 if [[ $# -ne 2 ]]; then
   print_help
-  exit 1
+  exit 10
 fi
 
 _verb=$1
 _hostname=$2
+
+if ! command -v op &>/dev/null
+then
+  echo "ERROR: op could not be found. Please install 1Password CLI and add to the PATH." 1>&2
+  exit 11
+fi
+
+op whoami &>/dev/null
+RETVAL=$?
+if [ $RETVAL -ne 0 ]; then
+  echo "ERROR: no account found for filter.  Try 'op signin' to log in." 1>&2
+  exit $RETVAL
+fi
 
 case $_verb in
   get)
@@ -41,7 +54,7 @@ case $_verb in
     RETVAL=$?
     if [ $RETVAL -eq 0 ]; then
       echo "ERROR: Entry already exists in 1Password for the item." 1>&2
-      exit 2
+      exit 13
     fi
     # Store the item.
     op item template get 'API Credential' | \
